name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2

      - name: Run linter
        run: golangci-lint run ./...

      - name: Build
        run: go build -v ./...

      - name: Run tests with coverage
        run: |
          mkdir -p test-results
          go test -v -coverprofile=coverage.out ./... | tee test-results/test.log

      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-results/test.log

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out
